### ISSUE TITLE
Extract controllers from routes folder

### ISSUE THREAD

**Issue by Farischt** [DamyanBG/real-estate-nodejs-be#63]
Routes folder should not contain the request flow. Create a separated folder that contains each controller. 

controllers
      - land 
      - ....
 
Code will be much easier to read for further contributions

**Comment by DamyanBG** [comment]
Okay, can you refactor the structure and show us a PR? Can you show us some articles for best practices which are related to the folder structure? Here we are newbies in NodeJS, so it will be interesting for us.

**Comment by Farischt** [comment]
Yes no pb, you should have a look for MVC  pattern (Model View Controller) (btw it is a language agnostic pattern). Since you have a separated frontend you should not consider the part related to the View. 
Here are some posts about the MVC pattern in Node.js : 
    - https://blog.logrocket.com/building-structuring-node-js-mvc-application/
    - https://dev.to/eetukudo_/understanding-mvc-pattern-in-nodejs-2bdn
    - https://taylorackley.medium.com/simple-and-minimalist-mvc-architecture-pattern-for-node-express-cb542287a144

**Comment by Farischt** [comment]
I'll show you how to do it for "land" entity

**Comment by DamyanBG** [comment]
I think that the Model-View-Controller (MVC) pattern is typically used for web applications that have a user interface (UI) and a server-side component, rather than for purely server-side applications such as a REST API.

In a web application that uses the MVC pattern, the view represents the UI of the application and is responsible for rendering the content and layout to the user. In a REST API, however, there is no UI as such, and the API simply exposes a set of endpoints that can be accessed by client applications to perform various actions.

As a result, the MVC pattern may not be the most appropriate architectural pattern for a REST API.
